#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path '../lib', __dir__

require 'whatthegem'

name, cmd, *args = ARGV

cmd ||= 'info'
gem = WhatTheGem::Gem.fetch(name)

WhatTheGem::Command.fetch(cmd).call(gem, *args)

# WhatTheGem::Command.fetch(cmd).call(*args)